server:
  port: 88
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: hdgaadd
          uri: lb://client  # 配置服务，该服务name为注册在Nacos的
          predicates:
            - Path=/api/**  # 配置访问网关，需添加的前缀
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

